/home/suryatejadev/miniconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    main(args.config)
  File "main.py", line 25, in main
    os.path.join(exp_dir, 'logs')])
  File "../disease_forecast/utils.py", line 12, in create_dirs
    os.mkdir(path)
FileExistsError: [Errno 17] File exists: '../outputs/base_T_2_onehot'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

